Jaeger proxy
Pavkazzz/jaeger-proxy pull request #1
Opened 2020-01-23 17:36 UTC by Pavkazzz

2020-01-24 09:43 UTC, asteny commented on jaeger_proxy/main.py
> +    os.environ.clear()
а зачем?

2020-01-24 09:45 UTC, Pavkazzz commented on jaeger_proxy/main.py
> +group.add_argument("--http-login", type=str, default="edadeal")
🐊

2020-01-24 10:07 UTC, dizballanze requested changes

2020-01-24 10:07 UTC, dizballanze commented on jaeger_proxy/main.py
> +async def ping(*_):
request напиши, зачем там *_

2020-01-24 10:07 UTC, dizballanze commented on jaeger_proxy/main.py
> +class API(AIOHTTPService):
сделай отдельный файл для сервиса лучше

2020-01-24 10:07 UTC, dizballanze commented on jaeger_proxy/main.py
> +class Sender(PeriodicService):
Лучше отдельный файл для сервиса

2020-01-24 10:10 UTC, dizballanze commented on jaeger_proxy/main.py
> +    Sender.QUEUE.append((data, bypass_headers))
будет ООМ приходить и будешь терять данные, в карбон прокси не просто так в файл пишется

2020-01-24 10:29 UTC, Pavkazzz commented on jaeger_proxy/main.py
> +    os.environ.clear()
Чтобы никто не брал параметры из окружения

2020-01-24 10:39 UTC, Pavkazzz commented on jaeger_proxy/main.py
> +class API(AIOHTTPService):
👍

2020-01-24 10:39 UTC, Pavkazzz commented on jaeger_proxy/main.py
> +    Sender.QUEUE.append((data, bypass_headers))
Где пишется файл?

2020-01-24 10:39 UTC, Pavkazzz commented on jaeger_proxy/main.py
> +    Sender.QUEUE.append((data, bypass_headers))
https://github.com/mosquito/carbon-proxy/blob/master/carbon_proxy/server.py#L120

2020-01-27 05:51 UTC, asteny commented on jaeger_proxy/main.py
> +    os.environ.clear()
получается ты рассчитываешь при старте забрать переменные и очистить все? но если процесс будет убит и перезапущен переменных уже не будет. Ладно если мы весь контейнер перезапустит, а если это будет работать не в контейнере?

2020-01-27 11:10 UTC, Pavkazzz commented on jaeger_proxy/main.py
> +    os.environ.clear()
Не, он чистит только в текущем процессе и дочерних. При перезапуске они снова возьмутся от родителя

2020-01-28 18:05 UTC, merged